# Generated by Django 3.0.4 on 2020-08-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpro',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='userpro',
            old_name='hito',
            new_name='motoo',
        ),
    ]
