# Generated by Django 3.2.4 on 2021-06-17 15:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='img/avatar'),
        ),
    ]
