# Generated by Django 3.0.4 on 2020-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpro',
            options={'ordering': ('pk',)},
        ),
    ]
