# Generated by Django 3.0.4 on 2020-08-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200830_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='nickname',
            field=models.CharField(blank=True, default='user one', max_length=16, verbose_name='昵称'),
        ),
    ]
