# Generated by Django 3.0.4 on 2020-08-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userpro_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpro',
            old_name='user',
            new_name='uid',
        ),
    ]
