# Generated by Django 3.0.4 on 2020-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200830_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpro',
            options={'ordering': ('uid',)},
        ),
        migrations.AlterField(
            model_name='userpro',
            name='nickname',
            field=models.CharField(default='user one', max_length=16, verbose_name='昵称'),
        ),
    ]
