# Generated by Django 3.0.4 on 2020-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200830_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpro',
            options={'ordering': ('pk',)},
        ),
    ]
