# Generated by Django 3.0.4 on 2020-08-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200830_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpro',
            old_name='uid',
            new_name='user',
        ),
    ]
