# Generated by Django 3.0.4 on 2020-09-02 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20200830_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpro',
            name='nickname',
            field=models.CharField(default='User One', max_length=16, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pro', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
