# Generated by Django 3.0.4 on 2020-03-16 20:10

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=999)),
                ('who', models.CharField(max_length=32)),
                ('where', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='%Y/music/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=32)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-update',),
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='软件名')),
                ('version', models.CharField(max_length=10, verbose_name='版本号')),
                ('os', models.IntegerField(choices=[(1, 'Windows'), (2, 'Android'), (3, 'Chrome')], verbose_name='平台')),
                ('abstract', models.CharField(max_length=100, verbose_name='简介')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='%Y/img/software_logo/')),
                ('update', models.DateTimeField(auto_now=True)),
                ('link1', models.CharField(blank=True, max_length=9999)),
                ('link2', models.CharField(blank=True, max_length=9999)),
                ('link3', models.CharField(blank=True, max_length=9999)),
            ],
            options={
                'ordering': ('-update',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, unique=True, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='标题')),
                ('abstract', models.CharField(max_length=100, verbose_name='简介')),
                ('category', models.IntegerField(choices=[(1, 'Anime'), (2, 'Movie'), (3, 'Dorama'), (4, 'Chip')], verbose_name='类型')),
                ('sub', models.CharField(max_length=10, verbose_name='字幕')),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='%Y/img/video_cover/')),
                ('link1', models.CharField(blank=True, max_length=9999)),
                ('link2', models.CharField(blank=True, max_length=9999)),
                ('link3', models.CharField(blank=True, max_length=9999)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-update',),
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='%Y/img/')),
                ('md5', models.CharField(blank=True, max_length=128, unique=True)),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_imgs', to='backend.Software')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_imgs', to='backend.Video')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='标题')),
                ('abstract', models.CharField(max_length=40, verbose_name='摘要')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='%Y/img/article_img/')),
                ('markdown', models.FileField(blank=True, upload_to='%Y/markdown/')),
                ('update', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='backend.Tag')),
            ],
            options={
                'ordering': ('-update',),
            },
        ),
    ]
