# Generated by Django 3.0.4 on 2020-03-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=100, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='where',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hito',
            name='who',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
