# Generated by Django 3.0.4 on 2020-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hito',
        ),
        migrations.RemoveField(
            model_name='article',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=90, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
