# Generated by Django 3.0.4 on 2021-06-07 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='share',
            new_name='special',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
