# Generated by Django 3.0.4 on 2020-03-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200322_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hito',
            options={'ordering': ('-pk',)},
        ),
    ]
