# Generated by Django 3.0.4 on 2020-03-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200325_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='software',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
