# Generated by Django 3.0.4 on 2020-03-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200325_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='link3',
        ),
    ]
