# Generated by Django 3.0.4 on 2021-06-11 15:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210610_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='%Y/img/post_img/'),
        ),
    ]
