# Generated by Django 3.2.4 on 2021-06-17 15:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='img/post_img/'),
        ),
    ]
